chore: Specify tooling and dependencies
Layendan/NineAnimator-Tauri pull request #10
Opened 2022-12-06 01:35 UTC by zkourouma

- add link to Tauri install prerequisites to README
- add spec in package.json for minimum node version
- add rust toolchain specifying rust version

2022-12-06 02:23 UTC, Layendan commented
Thank you for this pull request!

Not gonna lie, I didn't expect people making pull requests this early.
But I'm glad that you made it.

2022-12-08 04:23 UTC, Layendan requested changes
Would it be possible to format what you added to the README such that it aligns with what already exists?

2022-12-08 04:23 UTC, Layendan commented on README.md
> +## Getting Started
Would it be possible to add a space between this and the next line as well adding a space between the next line and ## Features?
This would make it so that the formatting in the README stays consistent.

2022-12-08 14:10 UTC, zkourouma commented on README.md
> +## Getting Started
sure thing 86bdc9b

2022-12-08 19:10 UTC, Layendan approved these changes
Thank you the help!

2022-12-08 19:11 UTC, merged